version: "3.7"
services:
  flask:
      build:
        ./
      volumes: 
        - .:/home/appuser
      depends_on:
        - mysql
      ports:
        - "5000:5000"

  adminer:
      image: adminer
      ports:
        - 8888:8080

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_anunbis
    volumes:
      - ./src/database:/docker-entrypoint-initdb.d
    expose: 
      - "3306"
    command: --default-authentication-plugin=mysql_native_password